set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g set-clipboard on
set -g extended-keys always
set -as terminal-features ',xterm-kitty:clipboard:extkeys'

set -g mouse on

bind -n S-Left  previous-window
bind -n S-Right next-window

set -g status-style 'fg=#e4e4ef,bg=#181818'
set -g status-left  ' #[fg=#ffdd33,bold]#S #[fg=#484848]│ '
set -g status-right '#[fg=#484848]│ #[fg=#cc8c3c]%H:%M '
set -g status-left-length 40

set -g window-status-format         ' #I  #W '
set -g window-status-current-format ' #I  #W '
set -g window-status-style          'fg=#888888,bg=default'
set -g window-status-current-style  'fg=#181818,bg=#ffdd33,bold'
set -g window-status-activity-style 'fg=#f43841,bg=default'
set -g window-status-separator      ''

set -g pane-border-style        'fg=#333333'
set -g pane-active-border-style 'fg=#ffdd33'

set -g message-style 'fg=#181818,bg=#ffdd33'

run '~/.config/tmux/plugins/tpm/tpm'
